namespace db.booksdatamodelNamespace;

type BooksAgeGroup : String enum{
    Kids = 'KIDS';
    Adult = 'ADULT';
}


entity books {
    key ID          : UUID; // autogenerated unique identifier
        Title       : String;
        author      : String;
        price       : Decimal(10, 2);
        publishdate : DateTime; // date of publication
        digitalCopy : Boolean;
        bookAgeGroup : BooksAgeGroup;
}